services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: milan
      POSTGRES_PASSWORD: milan123
      POSTGRES_DB: milan_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
